services:
  db:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=hunter2
      - POSTGRES_USER=alex
      - POSTGRES_DB=shelter
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
       - "5432:5432"

  etl:
    build: .   
    command: https://shelterdata.s3.amazonaws.com/shelter1000.csv
    depends_on:
      - db


volumes:
  db_data:


# services:
#   web:
#     build: .
#     ports:
#       - "8000:5000"
#     volumes:
#       - .:/code
#     environment:
#       FLASK_DEBUG: "true"
#   redis:
#     image: "redis:alpine"